name: "AI-Reviwer"

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: Daniel-Sogbey/AutoPR-reviewer@v1
        with:
          togetherai_api_key: ${{secrets.TOGETHER_API_KEY}}
          github_token: ${{secrets.GITHUB_TOKEN}}